; -----------------------------------------------------------------------------
; Uses pbFreqOut to generate square waves and play music.
; The circuit:
; - piezo buzzer anode is attached to VIA port A pin 0.
; - piezo buzzer cathode is attached to ground VIA header pin.
;
; Martin Heermance <mheermance@gmail.com>
; -----------------------------------------------------------------------------

.include "ascii.inc"
.include "common.inc"
.include "pbasic.inc"
.include "print.inc"
.include "via.inc"
.include "w65c265Monitor.inc"

; Period values for musical notes in CPU cycles
NOTE_B0  = CLK_FREQ / 31
NOTE_C1  = CLK_FREQ / 33
NOTE_CS1 = CLK_FREQ / 35
NOTE_D1  = CLK_FREQ / 37
NOTE_DS1 = CLK_FREQ / 39
NOTE_E1  = CLK_FREQ / 41
NOTE_F1  = CLK_FREQ / 44
NOTE_FS1 = CLK_FREQ / 46
NOTE_G1  = CLK_FREQ / 49
NOTE_GS1 = CLK_FREQ / 52
NOTE_A1  = CLK_FREQ / 55
NOTE_AS1 = CLK_FREQ / 58
NOTE_B1  = CLK_FREQ / 62
NOTE_C2  = CLK_FREQ / 65
NOTE_CS2 = CLK_FREQ / 69
NOTE_D2  = CLK_FREQ / 73
NOTE_DS2 = CLK_FREQ / 78
NOTE_E2  = CLK_FREQ / 82
NOTE_F2  = CLK_FREQ / 87
NOTE_FS2 = CLK_FREQ / 93
NOTE_G2  = CLK_FREQ / 98
NOTE_GS2 = CLK_FREQ / 104
NOTE_A2  = CLK_FREQ / 110
NOTE_AS2 = CLK_FREQ / 117
NOTE_B2  = CLK_FREQ / 123
NOTE_C3  = CLK_FREQ / 131
NOTE_CS3 = CLK_FREQ / 139
NOTE_D3  = CLK_FREQ / 147
NOTE_DS3 = CLK_FREQ / 156
NOTE_E3  = CLK_FREQ / 165
NOTE_F3  = CLK_FREQ / 175
NOTE_FS3 = CLK_FREQ / 185
NOTE_G3  = CLK_FREQ / 196
NOTE_GS3 = CLK_FREQ / 208
NOTE_A3  = CLK_FREQ / 220
NOTE_AS3 = CLK_FREQ / 233
NOTE_B3  = CLK_FREQ / 247
NOTE_C4  = CLK_FREQ / 262
NOTE_CS4 = CLK_FREQ / 277
NOTE_D4  = CLK_FREQ / 294
NOTE_DS4 = CLK_FREQ / 311
NOTE_E4  = CLK_FREQ / 330
NOTE_F4  = CLK_FREQ / 349
NOTE_FS4 = CLK_FREQ / 370
NOTE_G4  = CLK_FREQ / 392
NOTE_GS4 = CLK_FREQ / 415
NOTE_A4  = CLK_FREQ / 440
NOTE_AS4 = CLK_FREQ / 466
NOTE_B4  = CLK_FREQ / 494
NOTE_C5  = CLK_FREQ / 523
NOTE_CS5 = CLK_FREQ / 554
NOTE_D5  = CLK_FREQ / 587
NOTE_DS5 = CLK_FREQ / 622
NOTE_E5  = CLK_FREQ / 659
NOTE_F5  = CLK_FREQ / 698
NOTE_FS5 = CLK_FREQ / 740
NOTE_G5  = CLK_FREQ / 784
NOTE_GS5 = CLK_FREQ / 831
NOTE_A5  = CLK_FREQ / 880
NOTE_AS5 = CLK_FREQ / 932
NOTE_B5  = CLK_FREQ / 988
NOTE_C6  = CLK_FREQ / 1047
NOTE_CS6 = CLK_FREQ / 1109
NOTE_D6  = CLK_FREQ / 1175
NOTE_DS6 = CLK_FREQ / 1245
NOTE_E6  = CLK_FREQ / 1319
NOTE_F6  = CLK_FREQ / 1397
NOTE_FS6 = CLK_FREQ / 1480
NOTE_G6  = CLK_FREQ / 1568
NOTE_GS6 = CLK_FREQ / 1661
NOTE_A6  = CLK_FREQ / 1760
NOTE_AS6 = CLK_FREQ / 1865
NOTE_B6  = CLK_FREQ / 1976
NOTE_C7  = CLK_FREQ / 2093
NOTE_CS7 = CLK_FREQ / 2217
NOTE_D7  = CLK_FREQ / 2349
NOTE_DS7 = CLK_FREQ / 2489
NOTE_E7  = CLK_FREQ / 2637
NOTE_F7  = CLK_FREQ / 2794
NOTE_FS7 = CLK_FREQ / 2960
NOTE_G7  = CLK_FREQ / 3136
NOTE_GS7 = CLK_FREQ / 3322
NOTE_A7  = CLK_FREQ / 3520
NOTE_AS7 = CLK_FREQ / 3729
NOTE_B7  = CLK_FREQ / 3951
NOTE_C8  = CLK_FREQ / 4186
NOTE_CS8 = CLK_FREQ / 4435
NOTE_D8  = CLK_FREQ / 4699
NOTE_DS8 = CLK_FREQ / 4978

NOTE_WHOLE = 4000
NOTE_HALF = NOTE_WHOLE / 2
NOTE_QUARTER = NOTE_WHOLE / 4
NOTE_EIGTH = NOTE_WHOLE / 8

BUZZER_PIN = 0			; Port B pin 0

PUBLIC main
	ON16MEM
	ON16X
	printcr			; start output on a newline
	jsr viaInit		; one time VIA initialization.

	pea $0000		; start with first note.
@while:	ply
	beq @return		; zero marks the end of the song.
	lda melody,y
	tax
	iny
	iny
	lda melody,y
	iny
	iny
	phy
	tay
	lda BUZZER_PIN
	jsr pbFreqOut
	bra @while
@return:
	pla
	rtl
ENDPUBLIC

; Pachelbel's Canon
; Note of the melody (in CPU cycles) followed by the duration.
; 2 means a half note, 4 a quarter note, 8 an eighteenth, 16 sixteenth, so on
; Duration is converted to machine cycles elsewhere
melody:
    .word NOTE_FS4,NOTE_HALF, NOTE_E4,NOTE_HALF
    .word NOTE_D4,NOTE_HALF,  NOTE_CS4,NOTE_HALF
    .word NOTE_B3,NOTE_HALF,  NOTE_A3,NOTE_HALF
    .word NOTE_B3,NOTE_HALF,  NOTE_CS4,NOTE_HALF
    .word NOTE_FS4,NOTE_HALF, NOTE_E4,NOTE_HALF
    .word NOTE_D4,NOTE_HALF,  NOTE_CS4,NOTE_HALF
    .word NOTE_B3,NOTE_HALF,  NOTE_A3,NOTE_HALF
    .word NOTE_B3,NOTE_HALF,  NOTE_CS4,NOTE_HALF
    .word NOTE_D4,NOTE_HALF,  NOTE_CS4,NOTE_HALF
    .word NOTE_B3,NOTE_HALF,  NOTE_A3,NOTE_HALF
    .word NOTE_G3,NOTE_HALF,  NOTE_FS3,NOTE_HALF
    .word NOTE_G3,NOTE_HALF,  NOTE_A3,NOTE_HALF
    .word NOTE_D4,NOTE_QUARTER, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_A4,NOTE_QUARTER, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH
    .word NOTE_A4,NOTE_QUARTER, NOTE_B3,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH, NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH
    .word NOTE_FS4,NOTE_QUARTER, NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH, NOTE_FS4,NOTE_QUARTER, NOTE_FS3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH
    .word NOTE_A3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH, NOTE_FS3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH, NOTE_A3,NOTE_HALF
    .word NOTE_G3,NOTE_QUARTER, NOTE_B3,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_G3,NOTE_QUARTER, NOTE_FS3,NOTE_EIGTH, NOTE_E3,NOTE_EIGTH
    .word NOTE_FS3,NOTE_QUARTER, NOTE_D3,NOTE_EIGTH, NOTE_E3,NOTE_EIGTH, NOTE_FS3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_EIGTH
    .word NOTE_G3,NOTE_QUARTER, NOTE_B3,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_QUARTER, NOTE_CS4,NOTE_EIGTH, NOTE_D4,NOTE_EIGTH
    .word NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH, NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_A4,NOTE_HALF
    .word NOTE_A4,NOTE_QUARTER, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_A4,NOTE_QUARTER
    .word NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_A4,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH
    .word NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH, NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_FS4,NOTE_QUARTER, NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH
    .word NOTE_FS4,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH
    .word NOTE_CS4,NOTE_QUARTER, NOTE_B3,NOTE_QUARTER, NOTE_D4,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH, NOTE_B3,NOTE_QUARTER
    .word NOTE_A3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH, NOTE_A3,NOTE_QUARTER, NOTE_D3,NOTE_EIGTH, NOTE_E3,NOTE_EIGTH, NOTE_FS3,NOTE_EIGTH, NOTE_G3,NOTE_EIGTH
    .word NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_QUARTER, NOTE_G3,NOTE_QUARTER, NOTE_B3,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_QUARTER
    .word NOTE_CS4,NOTE_EIGTH, NOTE_D4,NOTE_EIGTH, NOTE_A3,NOTE_EIGTH, NOTE_B3,NOTE_EIGTH, NOTE_CS4,NOTE_EIGTH, NOTE_D4,NOTE_EIGTH, NOTE_E4,NOTE_EIGTH
    .word NOTE_FS4,NOTE_EIGTH, NOTE_G4,NOTE_EIGTH, NOTE_A4,NOTE_HALF
    .word 0,0
