; -----------------------------------------------------------------------------
; Uses pbFreqOut to generate square waves and play music.
; The circuit:
; - piezo buzzer anode is attached to VIA port A pin 0.
; - piezo buzzer cathode is attached to ground VIA header pin.
;
; Martin Heermance <mheermance@gmail.com>
; -----------------------------------------------------------------------------

.include "ascii.inc"
.include "common.inc"
.include "pbasic.inc"
.include "print.inc"
.include "via.inc"
.include "w65c265Monitor.inc"

; Tone generator register value
; N = (FCLK / (16 x F)) - 1
; F = desired frequency
; FCLK = FCLK input clock
; Hz values for musical notes scaled for CPU cycles.
N_B0  = (FCLK / (16 * 31)) - 1
N_C1  = (FCLK / (16 * 33)) - 1
N_CS1 = (FCLK / (16 * 35)) - 1
N_D1  = (FCLK / (16 * 37)) - 1
N_DS1 = (FCLK / (16 * 39)) - 1
N_E1  = (FCLK / (16 * 41)) - 1
N_F1  = (FCLK / (16 * 44)) - 1
N_FS1 = (FCLK / (16 * 46)) - 1
N_G1  = (FCLK / (16 * 49)) - 1
N_GS1 = (FCLK / (16 * 52)) - 1
N_A1  = (FCLK / (16 * 55)) - 1
N_AS1 = (FCLK / (16 * 58)) - 1
N_B1  = (FCLK / (16 * 62)) - 1
N_C2  = (FCLK / (16 * 65)) - 1
N_CS2 = (FCLK / (16 * 69)) - 1
N_D2  = (FCLK / (16 * 73)) - 1
N_DS2 = (FCLK / (16 * 78)) - 1
N_E2  = (FCLK / (16 * 82)) - 1
N_F2  = (FCLK / (16 * 87)) - 1
N_FS2 = (FCLK / (16 * 93)) - 1
N_G2  = (FCLK / (16 * 98)) - 1
N_GS2 = (FCLK / (16 * 104)) - 1
N_A2  = (FCLK / (16 * 110)) - 1
N_AS2 = (FCLK / (16 * 117)) - 1
N_B2  = (FCLK / (16 * 123)) - 1
N_C3  = (FCLK / (16 * 131)) - 1
N_CS3 = (FCLK / (16 * 139)) - 1
N_D3  = (FCLK / (16 * 147)) - 1
N_DS3 = (FCLK / (16 * 156)) - 1
N_E3  = (FCLK / (16 * 165)) - 1
N_F3  = (FCLK / (16 * 175)) - 1
N_FS3 = (FCLK / (16 * 185)) - 1
N_G3  = (FCLK / (16 * 196)) - 1
N_GS3 = (FCLK / (16 * 208)) - 1
N_A3  = (FCLK / (16 * 220)) - 1
N_AS3 = (FCLK / (16 * 233)) - 1
N_B3  = (FCLK / (16 * 247)) - 1
N_C4  = (FCLK / (16 * 262)) - 1
N_CS4 = (FCLK / (16 * 277)) - 1
N_D4  = (FCLK / (16 * 294)) - 1
N_DS4 = (FCLK / (16 * 311)) - 1
N_E4  = (FCLK / (16 * 330)) - 1
N_F4  = (FCLK / (16 * 349)) - 1
N_FS4 = (FCLK / (16 * 370)) - 1
N_G4  = (FCLK / (16 * 392)) - 1
N_GS4 = (FCLK / (16 * 415)) - 1
N_A4  = (FCLK / (16 * 440)) - 1
N_AS4 = (FCLK / (16 * 466)) - 1
N_B4  = (FCLK / (16 * 494)) - 1
N_C5  = (FCLK / (16 * 523)) - 1
N_CS5 = (FCLK / (16 * 554)) - 1
N_D5  = (FCLK / (16 * 587)) - 1
N_DS5 = (FCLK / (16 * 622)) - 1
N_E5  = (FCLK / (16 * 659)) - 1
N_F5  = (FCLK / (16 * 698)) - 1
N_FS5 = (FCLK / (16 * 740)) - 1
N_G5  = (FCLK / (16 * 784)) - 1
N_GS5 = (FCLK / (16 * 831)) - 1
N_A5  = (FCLK / (16 * 880)) - 1
N_AS5 = (FCLK / (16 * 932)) - 1
N_B5  = (FCLK / (16 * 988)) - 1
N_C6  = (FCLK / (16 * 1047)) - 1
N_CS6 = (FCLK / (16 * 1109)) - 1
N_D6  = (FCLK / (16 * 1175)) - 1
N_DS6 = (FCLK / (16 * 1245)) - 1
N_E6  = (FCLK / (16 * 1319)) - 1
N_F6  = (FCLK / (16 * 1397)) - 1
N_FS6 = (FCLK / (16 * 1480)) - 1
N_G6  = (FCLK / (16 * 1568)) - 1
N_GS6 = (FCLK / (16 * 1661)) - 1
N_A6  = (FCLK / (16 * 1760)) - 1
N_AS6 = (FCLK / (16 * 1865)) - 1
N_B6  = (FCLK / (16 * 1976)) - 1
N_C7  = (FCLK / (16 * 2093)) - 1
N_CS7 = (FCLK / (16 * 2217)) - 1
N_D7  = (FCLK / (16 * 2349)) - 1
N_DS7 = (FCLK / (16 * 2489)) - 1
N_E7  = (FCLK / (16 * 2637)) - 1
N_F7  = (FCLK / (16 * 2794)) - 1
N_FS7 = (FCLK / (16 * 2960)) - 1
N_G7  = (FCLK / (16 * 3136)) - 1
N_GS7 = (FCLK / (16 * 3322)) - 1
N_A7  = (FCLK / (16 * 3520)) - 1
N_AS7 = (FCLK / (16 * 3729)) - 1
N_B7  = (FCLK / (16 * 3951)) - 1
N_C8  = (FCLK / (16 * 4186)) - 1
N_CS8 = (FCLK / (16 * 4435)) - 1
N_D8  = (FCLK / (16 * 4699)) - 1
N_DS8 = (FCLK / (16 * 4978)) - 1

REST = $ffff

D_WHOLE = 2000
D_HALF = D_WHOLE / 2
D_QUARTER = D_WHOLE / 4
D_EIGHTH = D_WHOLE / 8
D_DHALF = D_HALF + D_QUARTER
D_DQUARTER = D_QUARTER + D_EIGHTH
D_DEIGHTH = D_EIGHTH + (D_EIGHTH / 2)

TG0 = 0				; Tone generator 0
TG1 = 1				; Tone generator 1

PUBLIC main
	ON16MEM
	ON16X
	printcr			; start output on a newline
	jsr viaInit		; one time VIA initialization.
	lda #pachelbel
	jsr playsong
	lda #mario
	jsr playsong
	rtl
ENDPUBLIC

.proc playsong
	phd			; save direct page register
	pha
	pea $0000		; start with first note.
	tsc			; transfer stack pointer to direct page reg
	tcd			; function local space is now direct page.

	POINTER = 3
	INDEX = 1
@while:	ldy INDEX
	lda (POINTER),y
	beq @return		; zero marks the end of the song.
	tax
	iny
	iny
	lda (POINTER),y
	iny
	iny
	sty INDEX
	cpx #REST
	bne @else
	jsr pbPause
	bra @while
@else:
	tay
	lda TG1
	jsr pbFreqOut
	bra @while

@return:
	pla			; clean up the stack
	pla
	pld
	rts
.endproc

; Pachelbel's Canon
; Note of the melody followed by the duration.
pachelbel:
    .word N_FS4,D_HALF, N_E4,D_HALF
    .word N_D4,D_HALF,  N_CS4,D_HALF
    .word N_B3,D_HALF,  N_A3,D_HALF
    .word N_B3,D_HALF,  N_CS4,D_HALF
    .word N_FS4,D_HALF, N_E4,D_HALF
    .word N_D4,D_HALF,  N_CS4,D_HALF
    .word N_B3,D_HALF,  N_A3,D_HALF
    .word N_B3,D_HALF,  N_CS4,D_HALF
    .word N_D4,D_HALF,  N_CS4,D_HALF
    .word N_B3,D_HALF,  N_A3,D_HALF
    .word N_G3,D_HALF,  N_FS3,D_HALF
    .word N_G3,D_HALF,  N_A3,D_HALF
    .word N_D4,D_QUARTER, N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_A4,D_QUARTER, N_FS4,D_EIGHTH, N_G4,D_EIGHTH
    .word N_A4,D_QUARTER, N_B3,D_EIGHTH, N_CS4,D_EIGHTH, N_D4,D_EIGHTH, N_E4,D_EIGHTH, N_FS4,D_EIGHTH, N_G4,D_EIGHTH
    .word N_FS4,D_QUARTER, N_D4,D_EIGHTH, N_E4,D_EIGHTH, N_FS4,D_QUARTER, N_FS3,D_EIGHTH, N_G3,D_EIGHTH
    .word N_A3,D_EIGHTH, N_G3,D_EIGHTH, N_FS3,D_EIGHTH, N_G3,D_EIGHTH, N_A3,D_HALF
    .word N_G3,D_QUARTER, N_B3,D_EIGHTH, N_A3,D_EIGHTH, N_G3,D_QUARTER, N_FS3,D_EIGHTH, N_E3,D_EIGHTH
    .word N_FS3,D_QUARTER, N_D3,D_EIGHTH, N_E3,D_EIGHTH, N_FS3,D_EIGHTH, N_G3,D_EIGHTH, N_A3,D_EIGHTH, N_B3,D_EIGHTH
    .word N_G3,D_QUARTER, N_B3,D_EIGHTH, N_A3,D_EIGHTH, N_B3,D_QUARTER, N_CS4,D_EIGHTH, N_D4,D_EIGHTH
    .word N_A3,D_EIGHTH, N_B3,D_EIGHTH, N_CS4,D_EIGHTH, N_D4,D_EIGHTH, N_E4,D_EIGHTH, N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_A4,D_HALF
    .word N_A4,D_QUARTER, N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_A4,D_QUARTER
    .word N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_A4,D_EIGHTH, N_A3,D_EIGHTH, N_B3,D_EIGHTH, N_CS4,D_EIGHTH
    .word N_D4,D_EIGHTH, N_E4,D_EIGHTH, N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_FS4,D_QUARTER, N_D4,D_EIGHTH, N_E4,D_EIGHTH
    .word N_FS4,D_EIGHTH, N_CS4,D_EIGHTH, N_A3,D_EIGHTH, N_A3,D_EIGHTH
    .word N_CS4,D_QUARTER, N_B3,D_QUARTER, N_D4,D_EIGHTH, N_CS4,D_EIGHTH, N_B3,D_QUARTER
    .word N_A3,D_EIGHTH, N_G3,D_EIGHTH, N_A3,D_QUARTER, N_D3,D_EIGHTH, N_E3,D_EIGHTH, N_FS3,D_EIGHTH, N_G3,D_EIGHTH
    .word N_A3,D_EIGHTH, N_B3,D_QUARTER, N_G3,D_QUARTER, N_B3,D_EIGHTH, N_A3,D_EIGHTH, N_B3,D_QUARTER
    .word N_CS4,D_EIGHTH, N_D4,D_EIGHTH, N_A3,D_EIGHTH, N_B3,D_EIGHTH, N_CS4,D_EIGHTH, N_D4,D_EIGHTH, N_E4,D_EIGHTH
    .word N_FS4,D_EIGHTH, N_G4,D_EIGHTH, N_A4,D_HALF
    .word 0,0

mario:
    .word N_E5,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_E5,D_EIGHTH
    .word N_G5,D_QUARTER, REST,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER
    .word N_C5,D_DQUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_E4,D_DQUARTER
    .word N_A4,D_QUARTER, N_B4,D_QUARTER, N_AS4,D_EIGHTH,N_A4,D_QUARTER
    .word N_G4,D_DEIGHTH, N_E5,D_DEIGHTH, N_G5,D_DEIGHTH, N_A5,D_QUARTER, N_F5,D_EIGHTH,N_G5,D_EIGHTH
    .word REST,D_EIGHTH,N_E5,D_QUARTER,N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_B4,D_DQUARTER
    .word N_C5,D_DQUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_E4,D_DQUARTER
    .word N_A4,D_QUARTER, N_B4,D_QUARTER, N_AS4,D_EIGHTH,N_A4,D_QUARTER
    .word N_G4,D_DEIGHTH, N_E5,D_DEIGHTH, N_G5,D_DEIGHTH, N_A5,D_QUARTER, N_F5,D_EIGHTH,N_G5,D_EIGHTH
    .word REST,D_EIGHTH,N_E5,D_QUARTER,N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_B4,D_DQUARTER

    .word REST,D_QUARTER, N_G5,D_EIGHTH,N_FS5,D_EIGHTH,N_F5,D_EIGHTH,N_DS5,D_QUARTER, N_E5,D_EIGHTH
    .word REST,D_EIGHTH,N_GS4,D_EIGHTH,N_A4,D_EIGHTH,N_C4,D_EIGHTH,REST,D_EIGHTH,N_A4,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_EIGHTH
    .word REST,D_QUARTER, N_DS5,D_QUARTER, REST,D_EIGHTH,N_D5,D_DQUARTER
    .word N_C5,D_HALF, REST,D_HALF
    .word REST,D_QUARTER, N_G5,D_EIGHTH,N_FS5,D_EIGHTH,N_F5,D_EIGHTH,N_DS5,D_QUARTER, N_E5,D_EIGHTH
    .word REST,D_EIGHTH,N_GS4,D_EIGHTH,N_A4,D_EIGHTH,N_C4,D_EIGHTH,REST,D_EIGHTH,N_A4,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_EIGHTH
    .word REST,D_QUARTER, N_DS5,D_QUARTER, REST,D_EIGHTH,N_D5,D_DQUARTER
    .word N_C5,D_HALF, REST,D_HALF
    .word N_C5,D_EIGHTH,N_C5,D_QUARTER, N_C5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_QUARTER
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_C5,D_EIGHTH,N_C5,D_QUARTER, N_C5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_E5,D_EIGHTH
    .word REST,D_WHOLE
    .word N_C5,D_EIGHTH,N_C5,D_QUARTER, N_C5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_QUARTER
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_E5,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_E5,D_QUARTER
    .word N_G5,D_QUARTER, REST,D_QUARTER, N_G4,D_QUARTER, REST,D_QUARTER
    .word N_C5,D_DQUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_E4,D_DQUARTER

    .word N_A4,D_QUARTER, N_B4,D_QUARTER, N_AS4,D_EIGHTH,N_A4,D_QUARTER
    .word N_G4,D_DEIGHTH, N_E5,D_DEIGHTH, N_G5,D_DEIGHTH, N_A5,D_QUARTER, N_F5,D_EIGHTH,N_G5,D_EIGHTH
    .word REST,D_EIGHTH,N_E5,D_QUARTER, N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_B4,D_DQUARTER
    .word N_C5,D_DQUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_E4,D_DQUARTER
    .word N_A4,D_QUARTER, N_B4,D_QUARTER, N_AS4,D_EIGHTH,N_A4,D_QUARTER
    .word N_G4,D_DEIGHTH, N_E5,D_DEIGHTH, N_G5,D_DEIGHTH, N_A5,D_QUARTER, N_F5,D_EIGHTH,N_G5,D_EIGHTH
    .word REST,D_EIGHTH,N_E5,D_QUARTER, N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_B4,D_DQUARTER
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_D5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_G5,D_DEIGHTH, N_F5,D_DEIGHTH

    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_B4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_F5,D_DEIGHTH, N_E5,D_DEIGHTH, N_D5,D_DEIGHTH
    .word N_C5,D_EIGHTH,N_E4,D_QUARTER, N_E4,D_EIGHTH,N_C4,D_HALF
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_D5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_G5,D_DEIGHTH, N_F5,D_DEIGHTH

    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_B4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_F5,D_DEIGHTH, N_E5,D_DEIGHTH, N_D5,D_DEIGHTH
    .word N_C5,D_EIGHTH,N_E4,D_QUARTER, N_E4,D_EIGHTH,N_C4,D_HALF
    .word N_C5,D_EIGHTH,N_C5,D_QUARTER, N_C5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_EIGHTH,N_E5,D_EIGHTH
    .word REST,D_WHOLE
    .word N_C5,D_EIGHTH,N_C5,D_QUARTER, N_C5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_D5,D_QUARTER
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_E5,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_E5,D_EIGHTH,REST,D_EIGHTH,N_C5,D_EIGHTH,N_E5,D_QUARTER
    .word N_G5,D_QUARTER, REST,D_QUARTER, N_G4,D_QUARTER, REST,D_QUARTER
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_D5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_A5,D_DEIGHTH, N_G5,D_DEIGHTH, N_F5,D_DEIGHTH

    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_A4,D_EIGHTH,N_G4,D_HALF
    .word N_E5,D_EIGHTH,N_C5,D_QUARTER, N_G4,D_EIGHTH,REST,D_QUARTER, N_GS4,D_QUARTER
    .word N_A4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_A4,D_HALF
    .word N_B4,D_EIGHTH,N_F5,D_QUARTER, N_F5,D_EIGHTH,N_F5,D_DEIGHTH, N_E5,D_DEIGHTH, N_D5,D_DEIGHTH
    .word N_C5,D_EIGHTH,N_E4,D_QUARTER, N_E4,D_EIGHTH,N_C4,D_HALF

	; game over sound
    .word N_C5,D_DQUARTER, N_G4,D_DQUARTER, N_E4,D_QUARTER
    .word N_A4,D_DEIGHTH, N_B4,D_DEIGHTH, N_A4,D_DEIGHTH, N_GS4,D_DEIGHTH, N_AS4,D_DEIGHTH, N_GS4,D_DEIGHTH
    .word N_G4,D_EIGHTH,N_D4,D_EIGHTH,N_E4,D_DHALF
    .word 0,0
