"""
Code generator.

Walks the AST and emits virtual-machine assembly text.
The output is architecture-independent; it uses the VM instruction set
(LIT, CALL, EXIT, ZBRANCH, etc.) which are later resolved to native
instructions by the target-specific macro file (vmachine.inc).

The generator also tracks:
  - a symbol table of constants and word names
  - a label counter for synthetic branch targets
  - a string literal pool (emitted at end of each word)
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import TextIO
import io

from .ast_nodes import (
    Program, ConstantDef, VariableDef, WordDef,
    OriginDirective, SegmentDirective,
    NumberLit, StringLit, PrintString, WordCall,
    IfThen, BeginUntil, BeginWhileRepeat, DoLoop,
    ASTNode,
)


# ---------------------------------------------------------------------------
# Built-in word → VM instruction mapping
# ---------------------------------------------------------------------------
# Words that compile directly to a single VM instruction (no CALL needed).

INLINE_OPS: dict[str, str] = {
    '@':      'FETCH',
    '!':      'STORE',
    'c@':     'BFETCH',
    'c!':     'BSTORE',
    '>r':     'TOR',
    'r>':     'RFROM',
    'dup':    'DUP',
    'drop':   'DROP',
    'nip':    'NIP',
    '+':      'ADD',
    '-':      'SUB',
    '*':      'STAR',
    '=':      'EQ',
    'emit':   'EMIT',
    'key':    'KEY',
    'type':   'TYPE',
    'cputs':  'CPUTS',
    'clear':  'CLEAR',
}

# Words that require a call to a runtime routine.
RUNTIME_CALLS: dict[str, str] = {
    '/':      'vm_slash',
    'mod':    'vm_mod',
    '/mod':   'vm_slashmod',
    'and':    'vm_and',
    'or':     'vm_or',
    'xor':    'vm_xor',
    'not':    'vm_not',
    'lshift': 'vm_lshift',
    'rshift': 'vm_rshift',
    '<':      'vm_lt',
    '>':      'vm_gt',
    '0=':     'vm_zeq',
    '0<':     'vm_zlt',
    'over':   'vm_over',
    'swap':   'vm_swap',
    'rot':    'vm_rot',
    '2dup':   'vm_2dup',
    '2drop':  'vm_2drop',
    'i':      'vm_i',
    'j':      'vm_j',
    'cr':     'vm_cr',
    'space':  'vm_space',
    'spaces': 'vm_spaces',
    '.':      'vm_dot',
    'u.':     'vm_udot',
    'allot':  'vm_allot',
    'cells':  'vm_cells',
    'cell+':  'vm_cellplus',
    'here':   'vm_here',
    'count':  'vm_count',
    'move':   'vm_move',
    'fill':   'vm_fill',
}


class CodeGenError(Exception):
    def __init__(self, msg, node: ASTNode | None = None):
        if node:
            super().__init__(f"Line {node.line}, col {node.col}: {msg}")
        else:
            super().__init__(msg)
        self.node = node


@dataclass
class CodeGenerator:
    out:          TextIO = field(default_factory=io.StringIO)
    _label_count: int    = field(default=0, init=False)
    _constants:   dict   = field(default_factory=dict, init=False)
    _variables:   set    = field(default_factory=set, init=False)
    _words:       set    = field(default_factory=set, init=False)
    _str_count:   int    = field(default=0, init=False)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def generate(self, program: Program) -> str:
        self._emit_file_header()
        for node in program.definitions:
            self._top_def(node)
        self._emit_file_footer()
        if isinstance(self.out, io.StringIO):
            return self.out.getvalue()
        return ''

    # ------------------------------------------------------------------
    # Emit helpers
    # ------------------------------------------------------------------

    def _emit(self, line: str = ''):
        print(line, file=self.out)

    def _emit_instr(self, instr: str, comment: str = ''):
        if comment:
            self._emit(f'    {instr:<20} ; {comment}')
        else:
            self._emit(f'    {instr}')

    def _emit_label(self, label: str):
        self._emit(f'{label}:')

    def _fresh_label(self, prefix='L') -> str:
        self._label_count += 1
        return f'{prefix}_{self._label_count:04d}'

    # ------------------------------------------------------------------
    # File-level boilerplate
    # ------------------------------------------------------------------

    def _emit_file_header(self):
        self._emit('; Generated by forthc — do not edit by hand')
        self._emit('; Include the target-specific vmachine.inc before this file.')
        self._emit('.include "vmachine.inc"')
        self._emit()

    def _emit_file_footer(self):
        self._emit()
        self._emit('; === end of generated code ===')

    # ------------------------------------------------------------------
    # Top-level definitions
    # ------------------------------------------------------------------

    def _top_def(self, node: ASTNode):
        if isinstance(node, ConstantDef):
            self._gen_constant(node)
        elif isinstance(node, VariableDef):
            self._gen_variable(node)
        elif isinstance(node, WordDef):
            self._gen_word(node)
        elif isinstance(node, OriginDirective):
            self._gen_origin(node)
        elif isinstance(node, SegmentDirective):
            self._gen_segment(node)
        else:
            raise CodeGenError(f"Unknown top-level node {type(node).__name__}", node)

    def _gen_constant(self, node: ConstantDef):
        self._emit(f'; constant {node.name}')
        self._emit(f'{node.name} = {node.value}')
        self._emit()
        self._constants[node.name] = node.value

    def _gen_variable(self, node: VariableDef):
        self._emit(f'; variable {node.name}')
        self._emit(f'{node.name}:')
        self._emit_instr('.word 0', f'storage for variable {node.name}')
        self._emit()
        self._variables.add(node.name)

    def _gen_word(self, node: WordDef):
        self._words.add(node.name)
        self._emit(f'; word definition: {node.name}')
        self._emit_label(node.name)
        # String pool for this word
        str_pool: list[tuple[str, str]] = []   # (label, text)
        self._gen_body(node.body, str_pool)
        self._emit_instr('EXIT', 'return from word')
        # Emit string literals after the EXIT
        for lbl, text in str_pool:
            self._emit_label(lbl)
            escaped = text.replace('"', '\\"')
            self._emit(f'    .byte "{escaped}", 0')
        self._emit()

    def _gen_origin(self, node: OriginDirective):
        self._emit(f'.org {node.address:#x}')
        self._emit()

    def _gen_segment(self, node: SegmentDirective):
        self._emit(f'.segment "{node.name}"')
        self._emit()

    # ------------------------------------------------------------------
    # Body code generation
    # ------------------------------------------------------------------

    def _gen_body(self, stmts: list, str_pool: list):
        for stmt in stmts:
            self._gen_stmt(stmt, str_pool)

    def _gen_stmt(self, node: ASTNode, str_pool: list):
        if isinstance(node, NumberLit):
            self._emit_instr(f'LIT {node.value}', f'push {node.value}')

        elif isinstance(node, StringLit):
            lbl = self._fresh_str_label()
            str_pool.append((lbl, node.text))
            self._emit_instr(f'LIT {lbl}',            'push string address')
            self._emit_instr(f'LIT {len(node.text)}', 'push string length')

        elif isinstance(node, PrintString):
            lbl = self._fresh_str_label()
            str_pool.append((lbl, node.text))
            self._emit_instr(f'LIT {lbl}', f'print: "{node.text[:30]}"')
            self._emit_instr('CPUTS',      'print null-terminated string')

        elif isinstance(node, WordCall):
            self._gen_word_call(node)

        elif isinstance(node, IfThen):
            self._gen_if(node, str_pool)

        elif isinstance(node, BeginUntil):
            self._gen_begin_until(node, str_pool)

        elif isinstance(node, BeginWhileRepeat):
            self._gen_begin_while_repeat(node, str_pool)

        elif isinstance(node, DoLoop):
            self._gen_do_loop(node, str_pool)

        else:
            raise CodeGenError(f"Unknown statement node {type(node).__name__}", node)

    def _gen_word_call(self, node: WordCall):
        name = node.name

        # Inline VM primitive?
        if name in INLINE_OPS:
            instr = INLINE_OPS[name]
            self._emit_instr(instr, f'( {name} )')
            return

        # Runtime call?
        if name in RUNTIME_CALLS:
            target = RUNTIME_CALLS[name]
            self._emit_instr(f'CALL {target}', f'( {name} )')
            return

        # Known user-defined word?
        if name in self._words or name in self._variables:
            self._emit_instr(f'CALL {name}', f'call user word')
            return

        # Known constant — treat as a literal (compile-time fold)
        if name in self._constants:
            val = self._constants[name]
            self._emit_instr(f'LIT {val}', f'constant {name} = {val}')
            return

        # Unknown — emit a forward CALL and let the assembler resolve it
        self._emit_instr(f'CALL {name}', f'forward ref / external')

    # ------------------------------------------------------------------
    # Control structures
    # ------------------------------------------------------------------

    def _gen_if(self, node: IfThen, str_pool: list):
        else_lbl = self._fresh_label('else')
        end_lbl  = self._fresh_label('endif')

        # ZBRANCH to else/end
        self._emit_instr(f'ZBRANCH {else_lbl}', 'if: branch if zero (false)')
        self._gen_body(node.consequent, str_pool)

        if node.alternate:
            # Jump over alternate
            self._emit_instr(f'CALL {end_lbl}',  'if: jump to endif')
            # (We use a ZBRANCH+CALL here; a real jump would be a separate
            #  BRANCH instruction — extend VM instruction set as needed.)
            self._emit_label(else_lbl)
            self._gen_body(node.alternate, str_pool)
        else:
            self._emit_label(else_lbl)

        self._emit_label(end_lbl)

    def _gen_begin_until(self, node: BeginUntil, str_pool: list):
        top_lbl = self._fresh_label('begin')
        self._emit_label(top_lbl)
        self._gen_body(node.body, str_pool)
        self._emit_instr(f'ZBRANCH {top_lbl}',
                         'until: loop if top-of-stack is zero (false)')

    def _gen_begin_while_repeat(self, node: BeginWhileRepeat, str_pool: list):
        top_lbl  = self._fresh_label('begin')
        end_lbl  = self._fresh_label('repeat')
        self._emit_label(top_lbl)
        self._gen_body(node.test, str_pool)
        self._emit_instr(f'ZBRANCH {end_lbl}', 'while: exit if zero (false)')
        self._gen_body(node.body, str_pool)
        # Jump back to top — reuse ZBRANCH trick with a "1 ZBRANCH" won't work;
        # emit a LIT 0 / ZBRANCH as an unconditional jump pattern, or add BRANCH.
        # For now we push 0 then ZBRANCH (always taken):
        self._emit_instr(f'LIT 0',             'repeat: unconditional jump back')
        self._emit_instr(f'ZBRANCH {top_lbl}', 'repeat: loop back')
        self._emit_label(end_lbl)

    def _gen_do_loop(self, node: DoLoop, str_pool: list):
        # Stack before DO: ( limit index -- )
        # We push both onto the return stack for I/J access.
        top_lbl = self._fresh_label('do')
        end_lbl = self._fresh_label('loop')
        self._emit_instr('TOR',             'do: push index to R')
        self._emit_instr('TOR',             'do: push limit to R')
        self._emit_label(top_lbl)
        self._gen_body(node.body, str_pool)
        # Loop increment: call runtime helper which increments R, compares
        # to limit, branches back or exits.
        self._emit_instr(f'CALL vm_do_loop_step', 'loop: increment and test')
        self._emit_instr(f'ZBRANCH {top_lbl}',    'loop: branch if not done')
        # Clean up return stack (limit was left there)
        self._emit_instr('RFROM',           'loop: discard limit from R')
        self._emit_instr('DROP',            'loop: drop limit')
        self._emit_label(end_lbl)

    # ------------------------------------------------------------------
    # String label helper
    # ------------------------------------------------------------------

    def _fresh_str_label(self) -> str:
        self._str_count += 1
        return f'_str_{self._str_count:04d}'


def generate(program: Program, out: TextIO | None = None) -> str:
    """
    Generate assembly text for *program*.
    If *out* is given, also write there.
    Always returns the generated text as a string.
    """
    buf = io.StringIO()
    cg  = CodeGenerator(out=buf)
    text = cg.generate(program)
    if out is not None:
        out.write(text)
    return text
