; -----------------------------------------------------------------------------
; Procedures exported from the conio module.
; Martin Heermance <mheermance@gmail.com>
; -----------------------------------------------------------------------------

;
; Aliases
;

;
; Importable functions.
;

.import conioInit
.import conioSetEcho
.import cgets
.import cputs
.import getch
.import ungetch
.import putch
