\ memory_test.fs - Memory access regression tests

\ @
VARIABLE FETCH-VAR
$BEEF FETCH-VAR !
T{ FETCH-VAR @ -> $BEEF }T

\ !
VARIABLE STORE-VAR
$BEEF STORE-VAR !
T{ $FEED STORE-VAR ! STORE-VAR @ -> $FEED }T

\ C@
CREATE CFETCH-BUF $43 C, $40 C,
T{ CFETCH-BUF C@ -> $43 }T

\ C!
VARIABLE CSTORE-VAR
$FFFF CSTORE-VAR !
T{ $24 CSTORE-VAR C! CSTORE-VAR C@ -> $24 }T

\ 2@
CREATE TWOFETCH-BUF $FEED , $BEEF ,
T{ TWOFETCH-BUF 2@ -> $FEED $BEEF }T

\ 2!
CREATE TWOSTORE-BUF 0 , 0 ,
T{ $FEED $BEEF TWOSTORE-BUF 2!
   TWOSTORE-BUF @
   TWOSTORE-BUF CELL+ @ -> $BEEF $FEED }T

\ ALIGNED
T{ $0057 ALIGNED -> $0058 }T
T{ $0064 ALIGNED -> $0064 }T

\ CHAR+
T{ $0057 CHAR+ -> $0058 }T

\ MOVE
CREATE MOVE-SRC  $48 C, $65 C, $6C C, $6C C, $6F C, $21 C, $20 C, $20 C,
CREATE MOVE-DST  $20 C, $20 C, $20 C, $20 C, $20 C, $20 C, $20 C, $20 C,
T{ MOVE-SRC MOVE-DST 8 MOVE
   MOVE-SRC 8 MOVE-DST 8 COMPARE -> 0 }T

\ FILL
CREATE FILL-DST  $20 C, $20 C, $20 C, $20 C, $20 C, $20 C, $20 C, $20 C,
T{ FILL-DST 8 $24 FILL
   FILL-DST C@ -> $24 }T
T{ FILL-DST 1 CHARS + C@ -> $24 }T
T{ FILL-DST 7 CHARS + C@ -> $24 }T

DONE
