\ memory_test.fs - Memory access regression tests

\ @
VARIABLE FETCH-VAR
$BEEF FETCH-VAR !
T{ FETCH-VAR @ -> $BEEF }T

\ !
VARIABLE STORE-VAR
$BEEF STORE-VAR !
T{ $FEED STORE-VAR ! STORE-VAR @ -> $FEED }T

\ C@
VARIABLE CFETCH-BUF
$0043 CFETCH-BUF !
T{ CFETCH-BUF C@ -> $43 }T

\ C!
VARIABLE CSTORE-VAR
$FFFF CSTORE-VAR !
T{ $24 CSTORE-VAR C! CSTORE-VAR C@ -> $24 }T

\ 2@
2VARIABLE TWOFETCH-BUF
$FEED $BEEF TWOFETCH-BUF 2!
T{ TWOFETCH-BUF 2@ -> $FEED $BEEF }T

\ 2!
2VARIABLE TWOSTORE-BUF
T{ $FEED $BEEF TWOSTORE-BUF 2!
   TWOSTORE-BUF @
   TWOSTORE-BUF CELL+ @ -> $BEEF $FEED }T

\ ALIGNED
T{ $0057 ALIGNED -> $0058 }T
T{ $0064 ALIGNED -> $0064 }T

\ CHAR+
T{ $0057 CHAR+ -> $0058 }T

VARIABLE MOVE-SRC 6 ALLOT
MOVE-SRC $48 C!
MOVE-SRC 1 CHARS + $65 C!
MOVE-SRC 2 CHARS + $6C C!
MOVE-SRC 3 CHARS + $6C C!
MOVE-SRC 4 CHARS + $6F C!
MOVE-SRC 5 CHARS + $21 C!
MOVE-SRC 6 CHARS + $20 C!
MOVE-SRC 7 CHARS + $20 C!

VARIABLE MOVE-DST 6 ALLOT
MOVE-DST 8 $20 FILL

T{ MOVE-SRC MOVE-DST 8 MOVE
   MOVE-SRC 8 MOVE-DST 8 COMPARE -> 0 }T

\ FILL
VARIABLE FILL-DST 6 ALLOT
T{ FILL-DST 8 $24 FILL
   FILL-DST C@ -> $24 }T
T{ FILL-DST 1 CHARS + C@ -> $24 }T
T{ FILL-DST 7 CHARS + C@ -> $24 }T

\ ERASE
VARIABLE ERASE-BUF 6 ALLOT
ERASE-BUF 8 $FF FILL       \ initialize to $FF
T{ ERASE-BUF 8 ERASE
   ERASE-BUF C@ -> 0 }T
T{ ERASE-BUF 3 CHARS + C@ -> 0 }T
T{ ERASE-BUF 7 CHARS + C@ -> 0 }T

DONE
